### PR TITLE
Added_documention_link_&_added_custom_panel_location

### PR DESCRIPTION
**Pull request by schroef**
- Added documentation link in Preferences menu
- Added custom location input for add-on location (category)

### CODE REVIEW

**Comment by mrossini-ethz** [comment]
Thanks for the nice work! However, could you please take under consideration the following ideas/changes?

- Why is the Tab "Relations" the default? It does not seem to belong there. Do you have a better suggestion?
- The Location in the `bl_info` (that appears in the add-on preferences) should be changed to whatever we choose to be the default Tab, i.e. `"3D View > Tools Panel > [whatever] > Camera Calibration PVR"`
- I like that the Tab can be configured now! Could you please put the input field to the right of the label `"Tab Category:"` rather than below?
- Could you remove the comment in the `unregister()` function? Or why is it commented?
- Your initial idea to have the link to the BA forum: A link should be placed in an appropriate section of the `README.md`.

I know, it's a lot of work. Could you please look into it?

**Comment by schroef** [comment]
I put it in relations cause thats one of the more top panels. My list is to clutterd  and the Misc is just a tiny one. I hate the vertical tabs, TOTALLY useless!!!!

They should make icons with hovers for that.
I do see a error in the console how ever
`Exception in module register(): '/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/camera-calibration-pvr.py'
Traceback (most recent call last):
  File "/Applications/blender-2.78a-OSX_10.6-x86_64/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/addon_utils.py", line 349, in enable
    mod.register()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/camera-calibration-pvr.py", line 943, in register
    bpy.utils.register_class(CameraCalibrationPanel)
ValueError: register_class(...): already registered as a subclass`

**Comment by mrossini-ethz** [comment]
Actually, it the "Tools" tab would be ok, I think. I did not like the "Misc" either, you know.

Why not
```
col = layout.column()
row = col.row()
row.label(...)
row.prop(...)
```
then more items coult be included in the future.

Oh, we need to make sure that in the README, all occurrences of "Misc" will be replaced with whatever we decide. And the link to the BA forum is still missing.

And yes, we should do something about the exception.

**Comment by schroef** [comment]
- Did the fix for the errors. looked like simple __NAME__ is good for all
- I redid your draw method, no need to define each item, its actually a column a row is when items need to be in 1 line. I also find this very confusing, im still looking for good info

found 2 great links
https://wiki.blender.org/index.php/Dev:Py/Scripts/Guidelines/Layouts
https://docs.blender.org/api/blender_python_api_2_63_17/info_best_practice.html

these helped me a lot, i was getting crazy how it really works

**Comment by mrossini-ethz** [comment]
Yes, I figured out the layouts a while ago. Have not updated the code though.

Alright, it's looking good! A few notes:

- I am happy with "Tools", let's leave it at that. If it does not suit somebody, they can now change it.
- The "Misc" panel is still mentioned 3 times in the README. Needs to be replaced with "Tools".
- There is still a `# col = row.column()` comment in the code that can be removed.
- Is the exception solved? Great!

Is it ok for you if I "squash and merge"?

**Comment by schroef** [comment]
Sorry errors are gone, but the custom panel location function doesnt work now...

**Comment by mrossini-ethz** [comment]
Yes, I just figured that out as well.

**Comment by schroef** [comment]
Okay all working again, with the fixed ;)

**Comment by mrossini-ethz** [comment]
Great! But did you forget to push it?

**Comment by schroef** [comment]
No i did push it, im using sourcetree and i've noticed sometimes when i push it, it doesnt get over. Commit solved it now.

Ive got a other project where i cant commit cause the master is from some one else, which has commits locked. Here i also see pushed edits not come over. Dont know whats wrong. I prefer to use sourcetree app, dont like how github app looks, also functions from sourcetree are better

**Comment by mrossini-ethz** [comment]
I told you it was a lot of work :-) Now the README still needs to be updated.

**Comment by schroef** [comment]
PS in your thread you talked about rotation. But what i meant with rotation is the image it self is rotated not rotated in the viewport. I see you check all kinds of items for the background image. But if the items in the image are rotated you cant fix that.

**Comment by schroef** [comment]
Ow i just added the BA link :)

**Comment by mrossini-ethz** [comment]
About the rotation: Please add an issue about that. It does not belong in this pull request.

**Comment by schroef** [comment]
Compared to your work this was a joke! How did you come up with all this code?

**Comment by mrossini-ethz** [comment]
Excellent, thank you very much! I will **squash** and **merge**, ok?

**Comment by mrossini-ethz** [comment]
What do you mean with "all this code"?

**Comment by schroef** [comment]
Well all the code in the addon, i really now jack about python. Seems all so complicated, all those mathematical numbers etc

**Comment by mrossini-ethz** [comment]
Oh, math is easy :-) I took most of the algorithm from a paper. It's mentioned at the very bottom of the README.

**Comment by schroef** [comment]
There are still some comments in the bottom, those can be taken out. Forgot them again:)

**Comment by schroef** [comment]
Pff that paper is even worse, understand jack about it

**Comment by mrossini-ethz** [comment]
Don't feel bad about that :-) This just means that you still have opportunity to learn ;-D

**Comment by mrossini-ethz** [comment]
Right now, I am learning how to handle a pull request on GitHub.

**Comment by mrossini-ethz** [comment]
Comments are still there ...

**Comment by mrossini-ethz** [comment]
I have removed the comments.

**Comment by mrossini-ethz** [comment]
It is done. Since I squashed the commits, you should delete your branch and pull from master.

**Comment by schroef** [comment]
Yes i did, its always a confusing how to do this stuff. Most things ive looked up are with the coding version. I like that i see changes now with this fork. WIth my other fork, different addon, i dont see that.

**Pull request merged**
